### ISSUE TITLE
Multi Domain Support

### ISSUE THREAD

**Issue by rajeshyadavdotnet** [tinesoft/ngx-cookieconsent#81] opened 2020-05-16 18:52 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version:
- ngx-cookieconsent version:
```

### Mention any other details that might be useful

I have two domains rajeshyadav.net and rajeshkumaryadav.com in the domain I set .com site which works fine but when I open .net site I click got it and refresh page again it shows, can we pass two domains ?

**Comment by tinesoft** [comment] 2020-05-23 04:13
Hi,

Please see #36, as this is a duplicate of it.

Besides, if you have 2 different domains, so I guess 2 different deployments,  maybe you can use 2 Angular's **environment.ts** to variabilize the domain in prod:

```
src/environment.ts
{
   cookieDomain: localhost
}
```

```
src/environment.prod1.ts
{
   cookieDomain: rajeshyadav.net
}
```

And

```
src/environment.prod2.ts
{
   cookieDomain: rajehyadav.com
}
```


In your `AppModule`, you will import  that `environment.ts`  file and use `environment.cookieDomain`  to set the domain on the `NgcCookieConsentConfig` object.

Then when you build/ deploy:

- `ng build --prod1` for domain1
- `ng build --prod2` for domain2

**Closed by tinesoft** 2020-05-23 04:13 UTC
