### ISSUE TITLE
.initialize$ callback is never called

### ISSUE THREAD

**Issue by FaabLondon** [tinesoft/ngx-cookieconsent#32] opened 2018-12-19 17:38 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
macOS High Sierra. Version 10.13.6

### Versions

Output from: `ng --version`, in case you are using Angular CLI.
Angular CLI: 6.1.5
Node: 8.9.4
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.9.2

### Repro steps

I followed the exact instructions given in the readme and it works great! I can see the consent popup, I can open it, close it, allow cookies, decline etc.
However, I never see the .initialize$ callback is never called. Why is that?
I wanted to use event.status to access the current status of the consent but nothing is happening (no error message either).
 
 this.initializeSubscription = this.ccService.initialize$.subscribe(
      (event: NgcInitializeEvent) => {
        console.log('init');
        // you can use this.ccService.getConfig() to do stuff...
      });

### The log given by the failure
No failure. The .initialize$ just doesn't fire up

### Desired functionality
.initialize$ to work
or find a way to access the current status of the consent. Alternatively, I will access the consent cookie directly.

**Comment by tinesoft** [comment] 2018-12-21 15:21
Hi @FaabLondon 

Thanks for your issue. I will have a closer look at it this weekend, 
and maybe you'll have it fixed and released in time for christmas! 🎄 🎁 

Stay tuned

Tine

**Comment by tinesoft** [comment] 2018-12-21 16:21
BTW, I've just remembered https://github.com/tinesoft/ngx-cookieconsent/commit/6cd260f
Which version are you on ? if prior to [v1.1.1](https://github.com/tinesoft/ngx-cookieconsent/releases/tag/v1.1.1), please update your dependecies and you should be good to go

**Comment by tinesoft** [comment] 2019-01-22 18:31
Closed due to inactivity

**Closed by tinesoft** 2019-01-22 18:31 UTC

**Comment by abhisekku14** [comment] 2019-06-06 05:06
Hello @tinesoft i have also came across the same problem.
.initialize$ just doesn't fire up. i have also tried printing some message on console but it didnt work.

**Comment by tinesoft** [comment] 2019-06-14 07:10
After https://github.com/tinesoft/ngx-cookieconsent/commit/6cd260f, i can confirm that this issue is no longer related to `ngx-cookieconsent`, but rather to `cookieconsent` itself, Please read https://github.com/osano/cookieconsent/issues/474, https://github.com/osano/cookieconsent/issues/389, and https://github.com/osano/cookieconsent/issues/352

So there is no much i can do... :-(

Can i ask what you intended to do if this event was triggered?
