### ISSUE TITLE
this.ccService.initialize$ subscription doesn't work

### ISSUE THREAD

**Issue by skobak** [tinesoft/ngx-cookieconsent#45] opened 2019-04-22 10:41 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version: ^3.1.0
- ngx-cookieconsent version: ^2.2.0
```

### OS Version?
> Windows 10.

### Angular, Node and al Versions?
Angular CLI: 7.3.6
Node: 11.3.0
OS: win32 x64
Angular: 7.2.10

### Repro steps
- install ngx-cookieconsent according to README
- Put subscribers to ngOnInt function
- Add the following code to 
```
 this.initializeSubscription = this.ccService.initialize$.subscribe(
      (event: NgcInitializeEvent) => {
        console.table(event); // Doesn't fire 
      },
    );
```

### Desired functionality
After page refresh or open the page again in a different tab I expect that I will see in a console 
an event object with STATUS: accept, decline or dismiss

**Comment by tinesoft** [comment] 2019-04-22 11:37
Hi,

Please provide the necessary minimum information as requested in the issue template (ng version, library version, etc...)

This helps providing a useful answer quickly

**Comment by skobak** [comment] 2019-04-22 18:05
> Hi,
> 
> Please provide the necessary minimum information as requested in the issue template (ng version, library version, etc...)
> 
> This helps providing a useful answer quickly

**Comment by skobak** [comment] 2019-04-22 18:06
> Hi,
> 
> Please provide the necessary minimum information as requested in the issue template (ng version, library version, etc...)
> 
> This helps providing a useful answer quickly

Thanks for the correction, not sure is it a bug but I update mine issue!

**Comment by RFreij** [comment] 2019-06-13 10:49
Same problem here:
```
Angular CLI: 7.3.8
Node: 10.16.0
OS: linux x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.30.0
ngx-cookieconsent@^2.2.2
cookieconsent@^3.1.1:
```

**Comment by strictd** [comment] 2019-08-03 17:39
This is due to the subscription firing when the service initializes. By the time your app component reads the Subject it's already fired. I changed the module to use a BehaviorSubject .. `this.initializeSource = new BehaviorSubject();` ..

**Comment by j0wey** [comment] 2019-09-06 12:48
Possibly caused by the [bug from the core library](https://github.com/osano/cookieconsent/issues/474)?
This is fixed now, but not yet committed to the master branch.

**Comment by rlyttle** [comment] 2020-08-01 11:48
Any update on a fix for this?

**Comment by tinesoft** [comment] 2021-07-07 16:32
Hi folks,

For future readers/googlers, please read https://github.com/tinesoft/ngx-cookieconsent/issues/97#issuecomment-875676240 as it should fixed the issue.

**Closed by tinesoft** 2021-07-07 16:32 UTC
