### ISSUE TITLE
Cookie popup has not yet been instantiated. Cannot invoke hasAnswered()

### ISSUE THREAD

**Issue by mebibou** [tinesoft/ngx-cookieconsent#97] opened 2021-03-01 17:08 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version: 3.1.1
- ngx-cookieconsent version: 2.2.3
```

### OS Version?

MacOS 11.2.2

### Angular, Node and al Versions?

```
Angular CLI: 11.2.2
Node: 12.5.0
OS: darwin x64

Angular: 11.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.2.2
@angular/cdk                    11.0.1
@angular/cli                    11.2.2
@angular/google-maps            11.0.0
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.6.3
typescript                      4.0.5
```

### Repro steps

```typescript
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor(
    private cookieService: NgcCookieConsentService
  ) {
    this.cookieService.initialize$.subscribe(() => setTimeout(() => this.init()));
  }

  private init() {
    return this.cookieService.hasAnswered() ? null : this.cookieService.open();
  }
}
```

### The log given by the failure

```
Cookie popup has not yet been instantiated. Cannot invoke hasAnswered()
```

### Desired functionality

I am calling `hasAnswered()` function when `.initialize$` fires, so I don't get how the error could tell me it is not instantiated.
Either `.initialize$` fires before it is initialized? or this is not the right way to call `hasAnswered()` ?

### Mention any other details that might be useful

This was caught by Sentry, so here is a bit more information about the device:

browser
Mobile Safari 14.0.3
browser.name
Mobile Safari
device
iPhone
device.family
iPhone
mechanism
instrument
os
iOS 14.4
os.name
iOS

**Comment by tinesoft** [comment] 2021-06-06 19:18
Hi @mebibou 

Sorry for the very late answer! I missed the notification on github...
Do you still face the issue? If so, please feel free to reopen the ticket

**Comment by mebibou** [comment] 2021-06-07 06:59
@tinesoft there hasnt been any changes since I posted the issue, so yes still facing it. I cannot reopen the issue

**Comment by tinesoft** [comment] 2021-07-05 21:44
Hi,

I could not reproduce the issue with the given information...
Maybe can you provide a minimal repro app on [Stackblitz](https://stackblitz.com)?

In the meantime, I would advise you to move the subscription code **out of the constructor**,
into the `ngOnInit()` method, as this is where it should be done normally:


```ts
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  	constructor(private cookieService: NgcCookieConsentService) {
  	}

	ngOnInit() {
    	this.cookieService.initialize$.subscribe(() => setTimeout(() => this.init()));
	}

  	private init() {
    	return this.cookieService.hasAnswered() ? null : this.cookieService.open();
  	}
}
```

**Comment by mebibou** [comment] 2021-07-06 08:28
@tinesoft the error does not happen systematically so providing an app won't help.

A few things:
- when to call `this.cookieService.initialize$.subscribe` should not change anything, as I am just subscribing to the event. If there is a problem with this, it would tell me something like `can not call function subscribe of undefined` or something like that. The `setTimeout(() => this.init())` will just be called when the event fires, which it only should when the `cookieService` is initialized
- the error is basically saying that I am calling `hasAnswered` before the service is initialized. **But** the `init` is only called **after** the intialized event has been fired...
- so it means the event can be sometimes fired even though it has not been initialized...

I do not know where the issue is because I didnt look closely at the code, but it obviously is a problem with `initialize$.next` being called when it should not

**Comment by tinesoft** [comment] 2021-07-07 14:57
Hi @mebibou,

Thanks to your input, I dug and found out that the current `initialize$` subscription is actually called when the `cookieconsent` library ***is initializing*** (see [docs](https://www.osano.com/cookieconsent/documentation/javascript-api/#hooks) here):

> onInitialise: function(status) {}
> 
> This is called on start up, with the current chosen compliance. It can be used to tell you if the user has already consented or not as soon as you initialise the tool.

So I've added a new `initiliazed$` event (not the extra "d" at the end), which is called when the `cookieconsent` library **has successfully been initialized**, i.e it is actually safe to call method like `NgcCookieConsentService.hasAnswered()` (see https://github.com/tinesoft/ngx-cookieconsent/pull/111).

I've also renamed the previous `initialize$` into `initializing$` to avoid further confusions (see https://github.com/tinesoft/ngx-cookieconsent/pull/112).


All of these changes will be released in the upcoming major version of the module (to be released soon ^^).

So stay tuned

**Closed by tinesoft** 2021-07-07 14:57 UTC

**Comment by mebibou** [comment] 2021-07-07 16:15
good stuff, thanks for finding the problem

**Comment by mebibou** [comment] 2021-09-30 07:14
So when is this new release coming exactly?

**Comment by tinesoft** [comment] 2021-10-03 08:31
Hi @mebibou ,

> So when is this new release coming exactly?

Hopefully soon! 😊

I want to add one more feature: a schematics to ease the installation/update of the library in new/existing Angular projects (i.e automatically adding of peerDependency on `cookieconsent`, update of `scripts/styles` in `angular.json`, etc)

Nothing complicated, but I just have to do some more cleaning/refactoring first.

So stay tuned!

**Comment by mebibou** [comment] 2022-03-24 09:41
it would be great to get a simply patch on the version for this, as I'm still getting that error multiple times per day
